### ISSUE TITLE
country code 

### ISSUE THREAD

**Issue by naisarg011** [fonibo/phonenumbers#1]
don't able to select country code may be something wrong with the controller

**Comment by themisir** [comment]
Can you give us a bit more details like screenshots, code or steps to reproduce?

**Comment by naisarg011** [comment]
//this is the image 
![image](https://user-images.githubusercontent.com/53462326/110825392-fbccdd80-82b9-11eb-998a-c1eb89203ec2.png)
//this is the code I have used to create the widget

```dart
Container(
                  padding:
                      EdgeInsets.symmetric(horizontal: 28.0, vertical: 10.0),
                  child: PhoneNumberFormField(
                    style: TextStyle(color: Colors.black),
                    autovalidateMode: AutovalidateMode.always,
                    controller: phoneNumberController,
                    countryCodeWidth: 122,
                    decoration: InputDecoration(
                      border: OutlineInputBorder(
                        borderRadius: BorderRadius.all(Radius.circular(20.0))
                        )
                      ),
                    ),
                  ),
```

**Comment by themisir** [comment]
Can you also write value of `phoneNumberController`?

**Comment by naisarg011** [comment]
yaay!!! 

late final PhoneNumberEditingController phoneNumberController;


//here I initialized the controller
```
@override
  void initState() {
    
    phoneNumberController = PhoneNumberEditingController();
    super.initState();
  }
```

**Comment by themisir** [comment]
Ok, I got it! The issue is caused because no default country is provided. I'll fix the issue soon. But you can fix the issue by providing default country.

You can define default country by initializing `PhoneNumberEditingController` using:

```dart
PhoneNumberEditingController. fromCountryCode('US');
```

**Comment by naisarg011** [comment]
yay thanks! for help.

**Comment by childon4god** [comment]
Country flag is not showing
