### ISSUE TITLE
Hint number text and spaces

### ISSUE THREAD

**Issue by aloisdeniel** [fonibo/phonenumbers#4]
Hello,

Thanks a lot!

It would be awesome to add the phone pattern for each country as a hint text.

Like : 

![image](https://user-images.githubusercontent.com/7687231/120002060-b83e6180-bfd4-11eb-996f-a176a26e609e.png)

**Comment by orestesgaolin** [comment]
Maybe the rules could include some kind of sections representation?

```dart
Country('United States', 'US', 1, LengthRule.sections([3,3,4], separator: '-')),
```

**Comment by themisir** [comment]
Sorry for the late response (cause I forget to enable notifications for this repo). I've not included this feature cause it's very hard to find reliable source for number patterns also those patterns might change on country / locale basis (some country numbers might have multiple number formats).
